### ISSUE TITLE
Error during fastqc-1 step

### ISSUE THREAD

**Issue by PHemarajata** [CDCgov/legionella_pneumophila_SBT_analysis#1]
Hi, I got the following error while trying to run the workflow using test data:

 Traceback (most recent call last):
  File "/usr/games/singularity", line 11, in <module>
    load_entry_point('Endgame-Singularity==1.0', 'gui_scripts', 'singularity')()
  File "/usr/lib/python3/dist-packages/singularity/__init__.py", line 78, in main
    i18n.set_language(force=True)
  File "/usr/lib/python3/dist-packages/singularity/code/i18n.py", line 109, in set_language
    gettext_language = gettext.translation(TEXTDOMAIN_PREFIX + 'messages', _get_main_localedir(), languages=[lang], fallback=True)
  File "/usr/lib/python3/dist-packages/singularity/code/i18n.py", line 56, in _get_main_localedir
    main_localedir = dirs.get_writable_file_in_dirs('locale', 'i18n')
  File "/usr/lib/python3/dist-packages/singularity/code/dirs.py", line 220, in get_writable_file_in_dirs
    write_dir = write_dirs[dir_name]
KeyError: 'i18n'

**Comment by jennahamlin** [comment]
Hi @PHemarajata

Unfortunately, I don't know how to interpret this error message at the moment. I just tested out the repo via a fresh install following the directions on the README and had success. Did you follow the install steps as listed on the README? If not, what were the commands you tried for installing and running?

**Comment by jhphan** [comment]
It looks like there's a conflict with 'singularity' on your machine. Unfortunately on Ubuntu and Debian, there's a package called 'singularity' that's actually a game. It conflicts with the 'singularity-container' package. Try uninstalling 'singularity' first, if that doesn't resolve it, then try reinstalling singularity-container.

**Comment by PHemarajata** [comment]
Hi! I tried the method @jhphan suggested and it worked. Thank you so much!
